### ISSUE TITLE
Л2 — Отладка

### ISSUE THREAD

**Issue by illinc** [lokehoke/labs_asm#1]
Сойдёт (ибо давно пора уже сдать).

10 - 1 (время) - 4 (нет никаких пояснений) + 2 (платформа — правда, неизвестно, какая именно) =  7

Устраивает?

**Comment by illinc** [comment]
Ой. А в журнале у меня записано, что вы её сдали уже.
И даже вовремя...

Так как 10+4 (в журнале) определённо больше, чем 7, то, наверное, менять ничего не стоит.

**Comment by lokehoke** [comment]
Да мы уже сдали 2 лабу, я её просто в репозиторий добавил

**Comment by illinc** [comment]
Ок.
